// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"simple-product-api/internal/product/delivery/http"
	"simple-product-api/internal/product/repository"
	"simple-product-api/internal/product/usecase"
	"simple-product-api/pkg/config"
	"simple-product-api/pkg/logger"
	"simple-product-api/pkg/redis"
)

import (
	_ "github.com/lib/pq"
)

// Injectors from wire.go:

func InitializeHandler(cfg *config.Config) (*http.Handler, error) {
	logrusLogger := logger.NewLogger()
	db, err := ProvidePostgres(cfg, logrusLogger)
	if err != nil {
		return nil, err
	}
	repositoryPostgre := repository.NewPostgresRepo(db, logrusLogger)
	client := redis.NewRedis(cfg)
	usecaseUsecase := usecase.NewUsecase(repositoryPostgre, client, logrusLogger)
	handler := http.NewHandler(usecaseUsecase, logrusLogger)
	return handler, nil
}
