// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	product "simple-product-api/internal/product"

	mock "github.com/stretchr/testify/mock"
)

// ProductUsecase is an autogenerated mock type for the ProductUsecase type
type ProductUsecase struct {
	mock.Mock
}

type ProductUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductUsecase) EXPECT() *ProductUsecase_Expecter {
	return &ProductUsecase_Expecter{mock: &_m.Mock}
}

// CreateProduct provides a mock function with given fields: ctx, p
func (_m *ProductUsecase) CreateProduct(ctx context.Context, p *product.Product) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *product.Product) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProductUsecase_CreateProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProduct'
type ProductUsecase_CreateProduct_Call struct {
	*mock.Call
}

// CreateProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - p *product.Product
func (_e *ProductUsecase_Expecter) CreateProduct(ctx interface{}, p interface{}) *ProductUsecase_CreateProduct_Call {
	return &ProductUsecase_CreateProduct_Call{Call: _e.mock.On("CreateProduct", ctx, p)}
}

func (_c *ProductUsecase_CreateProduct_Call) Run(run func(ctx context.Context, p *product.Product)) *ProductUsecase_CreateProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*product.Product))
	})
	return _c
}

func (_c *ProductUsecase_CreateProduct_Call) Return(_a0 error) *ProductUsecase_CreateProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ProductUsecase_CreateProduct_Call) RunAndReturn(run func(context.Context, *product.Product) error) *ProductUsecase_CreateProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetProductByID provides a mock function with given fields: ctx, id
func (_m *ProductUsecase) GetProductByID(ctx context.Context, id string) (*product.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *product.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*product.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *product.Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*product.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductUsecase_GetProductByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProductByID'
type ProductUsecase_GetProductByID_Call struct {
	*mock.Call
}

// GetProductByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *ProductUsecase_Expecter) GetProductByID(ctx interface{}, id interface{}) *ProductUsecase_GetProductByID_Call {
	return &ProductUsecase_GetProductByID_Call{Call: _e.mock.On("GetProductByID", ctx, id)}
}

func (_c *ProductUsecase_GetProductByID_Call) Run(run func(ctx context.Context, id string)) *ProductUsecase_GetProductByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ProductUsecase_GetProductByID_Call) Return(_a0 *product.Product, _a1 error) *ProductUsecase_GetProductByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductUsecase_GetProductByID_Call) RunAndReturn(run func(context.Context, string) (*product.Product, error)) *ProductUsecase_GetProductByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListProduct provides a mock function with given fields: ctx, filter
func (_m *ProductUsecase) ListProduct(ctx context.Context, filter product.ListFilter) ([]product.Product, int, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListProduct")
	}

	var r0 []product.Product
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, product.ListFilter) ([]product.Product, int, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, product.ListFilter) []product.Product); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]product.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, product.ListFilter) int); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, product.ListFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ProductUsecase_ListProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProduct'
type ProductUsecase_ListProduct_Call struct {
	*mock.Call
}

// ListProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - filter product.ListFilter
func (_e *ProductUsecase_Expecter) ListProduct(ctx interface{}, filter interface{}) *ProductUsecase_ListProduct_Call {
	return &ProductUsecase_ListProduct_Call{Call: _e.mock.On("ListProduct", ctx, filter)}
}

func (_c *ProductUsecase_ListProduct_Call) Run(run func(ctx context.Context, filter product.ListFilter)) *ProductUsecase_ListProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(product.ListFilter))
	})
	return _c
}

func (_c *ProductUsecase_ListProduct_Call) Return(_a0 []product.Product, _a1 int, _a2 error) *ProductUsecase_ListProduct_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *ProductUsecase_ListProduct_Call) RunAndReturn(run func(context.Context, product.ListFilter) ([]product.Product, int, error)) *ProductUsecase_ListProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewProductUsecase creates a new instance of ProductUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductUsecase {
	mock := &ProductUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
